# Generated by Django 4.1.7 on 2023-04-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.CharField(max_length=165)),
                ('slug', models.SlugField()),
                ('tempo_preparo', models.IntegerField()),
                ('unidade_tempo_preparo', models.CharField(max_length=65)),
                ('porcoes', models.ImageField(upload_to='')),
                ('unidade_porcoes', models.CharField(max_length=65)),
                ('modo_preparo', models.TextField()),
                ('modo_preparo_html', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_publicado', models.BooleanField(default=False)),
                ('receita_imagem', models.ImageField(upload_to='receitas/receitas_imagens/%d/%m/%Y/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
            ],
        ),
    ]
