# Generated by Django 4.1.7 on 2023-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='porcoes',
            field=models.IntegerField(),
        ),
    ]
