# Generated by Django 4.1.7 on 2023-06-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receitas_porcoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='receita_imagem',
            field=models.ImageField(blank=True, default='', upload_to='receitas/receitas_imagens/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
